### full random

GET http://localhost:5000/api/profiles

### avec des morceaux choisis par l'utilisateur

GET http://localhost:5000/api/profiles?name=john

### JSON

POST http://localhost:5000/api/profile
Content-Type: application/json

{
    "name": "Jean Castex",
    "job": "web devlopper",
    "address": "625 Shetland street",
    "country": "polka"
}